### ISSUE TITLE
MM crash after install the Module

### ISSUE THREAD

**Issue by rbrueckner82** [djerik/MMM-HomeConnect#10]
Hi,

i installed the dependencies, without any error "npm install"

`Dez 19 10:24:04 magicmirror node[489677]: [2024-12-19 10:24:04.468] [ERROR] Error [ERR_REQUIRE_ESM]: require() of ES Module /opt/MagicMirror/modules/MMM-HomeConnect/node_modules/node-fetch/src/index.js from /opt/MagicMirror/modules/MMM-HomeConnect/node_modules/home-connect-js/lib/utils.js not supported.
Dez 19 10:24:04 magicmirror node[489677]: Instead change the require of index.js in /opt/MagicMirror/modules/MMM-HomeConnect/node_modules/home-connect-js/lib/utils.js to a dynamic import() which is available in all CommonJS modules.
Dez 19 10:24:04 magicmirror node[489677]:     at Object.<anonymous> (/opt/MagicMirror/modules/MMM-HomeConnect/node_modules/home-connect-js/lib/utils.js:2:15)
Dez 19 10:24:04 magicmirror node[489677]:     at Object.<anonymous> (/opt/MagicMirror/modules/MMM-HomeConnect/node_modules/home-connect-js/main.js:2:15) {
Dez 19 10:24:04 magicmirror node[489677]:   code: 'ERR_REQUIRE_ESM'
Dez 19 10:24:04 magicmirror node[489677]: }
`

**Comment by rbrueckner82** [comment]
the solution

npm uninstall node-fetch && npm install node-fetch@2

**Comment by rbrueckner82** [comment]
the solution

npm uninstall node-fetch && npm install node-fetch@2
